[project]
name = "minimal-mlops"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.9"
dependencies = [
    "numpy>=2.0.2",
]

[tool.hatch.build.targets.wheel]
packages = ["minimal_mlops"]
